Fixed missing argument label 'preferredTimescale'
Fixed a Flutter iOS build error.

error: missing argument label 'preferredTimescale:' in call
                        player?.player?.seek(to: CMTimeMakeWithSeconds(Float64(positionInMillis / 1000), Int32(NSEC_PER_SEC)))
                                                                      ^
                                                                                                         preferredTimescale:

Could not build the precompiled application for the device.

Error launching application on iPhone.